// ===== ТОВАРЫ (ассортимент) =====
const products = [
    // Rick and Morty Bad acid (15)
    { id: 1, name: 'Ананасовый леденец', brand: 'Rick and Morty Bad acid', price: 15, emoji: '🍍' },
    { id: 2, name: 'Киви лайм', brand: 'Rick and Morty Bad acid', price: 15, emoji: '🥝' },
    { id: 3, name: 'Клюква лайм', brand: 'Rick and Morty Bad acid', price: 15, emoji: '🍒' },
    { id: 4, name: 'Вишня клюква', brand: 'Rick and Morty Bad acid', price: 15, emoji: '🍒' },
    // Catswill extra (15)
    { id: 5, name: 'Кислый швепс грейпфрут', brand: 'Catswill extra', price: 15, emoji: '🍊' },
    // Подонки Подгон (15)
    { id: 6, name: 'Апельсин мята', brand: 'Подонки Подгон', price: 15, emoji: '🍊' },
    { id: 7, name: 'Апельсин', brand: 'Подонки Подгон', price: 15, emoji: '🍊' },
    // Подонки (15)
    { id: 8, name: 'Кола сода айс (критикал)', brand: 'Подонки', price: 15, emoji: '🥤' },
    // Подонки Блуд (15)
    { id: 9, name: 'Черная смородина', brand: 'Подонки Блуд', price: 15, emoji: '🫐' },
    { id: 10, name: 'Классический бабл гам', brand: 'Подонки Блуд', price: 15, emoji: '🍬' },
    { id: 11, name: 'Яблоко виноград', brand: 'Подонки Блуд', price: 15, emoji: '🍏' },
    { id: 12, name: 'Персиковый лимонад', brand: 'Подонки Блуд', price: 15, emoji: '🍑' },
    { id: 13, name: 'Скитлс', brand: 'Подонки Блуд', price: 15, emoji: '🍬' },
    { id: 14, name: 'Сочная малина', brand: 'Подонки Блуд', price: 15, emoji: '🍓' },
    { id: 15, name: 'Виноград черника', brand: 'Подонки Блуд', price: 15, emoji: '🍇' },
    { id: 16, name: 'Конфеты смородина мята', brand: 'Подонки Блуд', price: 15, emoji: '🍬' },
    { id: 17, name: 'Брусничный морс', brand: 'Подонки Блуд', price: 15, emoji: '🍒' },
    { id: 18, name: 'Кислые вишневые червячки', brand: 'Подонки Блуд', price: 15, emoji: '🍒' },
    { id: 19, name: 'Банан клубника', brand: 'Подонки Блуд', price: 15, emoji: '🍌' },
    { id: 20, name: 'Клубника ежевика', brand: 'Подонки Блуд', price: 15, emoji: '🍓' },
    // Подонки инферно (17)
    { id: 21, name: 'Клубника грейпфрут малина', brand: 'Подонки инферно', price: 17, emoji: '🍓' },
    { id: 22, name: 'Клубничная шипучка', brand: 'Подонки инферно', price: 17, emoji: '🍓' },
    { id: 23, name: 'Клубника банан', brand: 'Подонки инферно', price: 17, emoji: '🍌' },
    // Anime love zombi (17)
    { id: 24, name: 'Алоэ виноград', brand: 'Anime love zombi', price: 17, emoji: '🍇' },
    { id: 25, name: 'Киви клубника', brand: 'Anime love zombi', price: 17, emoji: '🥝' },
    { id: 26, name: 'Персиковый шейк', brand: 'Anime love zombi', price: 17, emoji: '🍑' },
    { id: 27, name: 'Морозный рэдбул', brand: 'Anime love zombi', price: 17, emoji: '🐂' },
    { id: 28, name: 'Арбузный бабл гам', brand: 'Anime love zombi', price: 17, emoji: '🍉' },
    { id: 29, name: 'Клубничный леденец', brand: 'Anime love zombi', price: 17, emoji: '🍓' },
    { id: 30, name: 'Ананас киви', brand: 'Anime love zombi', price: 17, emoji: '🍍' },
    { id: 31, name: 'Малина с кислинкой', brand: 'Anime love zombi', price: 17, emoji: '🍓' },
    { id: 32, name: 'Фанта маракуйя', brand: 'Anime love zombi', price: 17, emoji: '🍊' },
    { id: 33, name: 'Лесной микс', brand: 'Anime love zombi', price: 17, emoji: '🌲' },
    { id: 34, name: 'Мандариновая фанта', brand: 'Anime love zombi', price: 17, emoji: '🍊' },
    { id: 35, name: 'Вишня лед', brand: 'Anime love zombi', price: 17, emoji: '🍒' },
    { id: 36, name: 'Ежевичный лимонад', brand: 'Anime love zombi', price: 17, emoji: '🍇' },
    { id: 37, name: 'Яблоко персик', brand: 'Anime love zombi', price: 17, emoji: '🍏' },
    { id: 38, name: 'Клубнично-вишневый лимонад', brand: 'Anime love zombi', price: 17, emoji: '🍓' },
    { id: 39, name: 'Клубника банан', brand: 'Anime love zombi', price: 17, emoji: '🍌' },
    { id: 40, name: 'Яблоко виноград', brand: 'Anime love zombi', price: 17, emoji: '🍏' },
    { id: 41, name: 'Энергетик виноград', brand: 'Anime love zombi', price: 17, emoji: '⚡' },
    // Long злой (17)
    { id: 42, name: 'Морс из лесных ягод', brand: 'Long злой', price: 17, emoji: '🫐' },
    { id: 43, name: 'Мандарин персик', brand: 'Long злой', price: 17, emoji: '🍊' },
    { id: 44, name: 'Клюква апельсин', brand: 'Long злой', price: 17, emoji: '🍒' },
    { id: 45, name: 'Виноград арбуз', brand: 'Long злой', price: 17, emoji: '🍇' },
    { id: 46, name: 'Клубника банан', brand: 'Long злой', price: 17, emoji: '🍌' },
    { id: 47, name: 'Фруктовый мармелад', brand: 'Long злой', price: 17, emoji: '🍬' },
    { id: 48, name: 'Виноградный чупа-чупс', brand: 'Long злой', price: 17, emoji: '🍬' },
    { id: 49, name: 'Мята спрайт', brand: 'Long злой', price: 17, emoji: '🌿' },
    { id: 50, name: 'Персик абрикос', brand: 'Long злой', price: 17, emoji: '🍑' },
    { id: 51, name: 'Малиновая газировка', brand: 'Long злой', price: 17, emoji: '🍓' },
    // Rick and Morty & catswill (18)
    { id: 52, name: 'Арбуз морозная черешня', brand: 'Rick and Morty & catswill', price: 18, emoji: '🍉' },
    { id: 53, name: 'Фрутелла лайм лимон малина', brand: 'Rick and Morty & catswill', price: 18, emoji: '🍋' },
    { id: 54, name: 'Малина яблоко лед', brand: 'Rick and Morty & catswill', price: 18, emoji: '🍓' },
    { id: 55, name: 'Кислые ленточки клубника ежевика', brand: 'Rick and Morty & catswill', price: 18, emoji: '🍓' },
    { id: 56, name: 'Голубика арбуз лед', brand: 'Rick and Morty & catswill', price: 18, emoji: '🫐' },
    { id: 57, name: 'Банан дыня мята', brand: 'Rick and Morty & catswill', price: 18, emoji: '🍌' },
];
